---
language: go
os:
  - linux
  - osx
go:
  - 1.9.x
  - tip

before_install:
  - go get github.com/mattn/goveralls
script:
  - make test
  - make
after_success:
  - $HOME/gopath/bin/goveralls -service=travis-ci
